Run bashly generate

diff --git a/mush b/mush
--- a/mush
+++ b/mush
@@ -36,6 +36,8 @@ mush_usage() {
   printf "%s\n" "Commands:"
   printf "  %s   Initialize the mush\n" "init   "
   printf "  %s   Add a new user\n" "useradd"
+  printf "  %s   Delete a user\n" "userdel"
+  printf "  %s   List all users\n" "list   "
   echo
 
   # :command.long_usage
@@ -137,6 +139,78 @@ mush_useradd_usage() {
     printf "    Traffic limit of the new user in GB\n"
     printf "    Default: 20\n"
     echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+mush_userdel_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "mush userdel - Delete a user\n"
+    echo
+
+  else
+    printf "mush userdel - Delete a user\n"
+    echo
+
+  fi
+
+  printf "Alias: d\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  mush userdel USERNAME\n"
+  printf "  mush userdel --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
+    echo
+
+    # :command.usage_args
+    printf "%s\n" "Arguments:"
+
+    # :argument.usage
+    printf "  %s\n" "USERNAME"
+    printf "    Username of the user to delete\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+mush_list_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "mush list - List all users\n"
+    echo
+
+  else
+    printf "mush list - List all users\n"
+    echo
+
+  fi
+
+  printf "Alias: l\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  mush list\n"
+  printf "  mush list --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -262,8 +336,9 @@ mush_useradd_command() {
   port=$(cat $PORT_FILE)
   echo $((port + 1)) > $PORT_FILE
   echo "Match LocalPort $port" >> /etc/ssh/sshd_config
-  echo "AllowUser $username" >> /etc/ssh/sshd_config
+  echo -e "\tAllowUsers $username" >> /etc/ssh/sshd_config
   # Also open port
+  systemctl restart ssh
 
   iptables -N ssh_$username
   iptables -A OUTPUT -p tcp --sport $port -j ssh_$username
@@ -275,6 +350,26 @@ mush_useradd_command() {
   echo "Username: $username"
   echo "Password: $password"
   echo "Port: $port"
+
+}
+
+# :command.function
+mush_userdel_command() {
+  # src/userdel_command.sh
+  echo "# this file is located in 'src/userdel_command.sh'"
+  echo "# code for 'mush userdel' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
+
+}
+
+# :command.function
+mush_list_command() {
+  # src/list_command.sh
+  echo "# this file is located in 'src/list_command.sh'"
+  echo "# code for 'mush list' goes here"
+  echo "# you can edit it freely and regenerate (it will not be overwritten)"
+  inspect_args
 
 }
 
@@ -318,6 +413,20 @@ parse_requirements() {
       action="useradd"
       shift
       mush_useradd_parse_requirements "$@"
+      shift $#
+      ;;
+
+    userdel | d)
+      action="userdel"
+      shift
+      mush_userdel_parse_requirements "$@"
+      shift $#
+      ;;
+
+    list | l)
+      action="list"
+      shift
+      mush_list_parse_requirements "$@"
       shift $#
       ;;
 
@@ -515,6 +624,106 @@ mush_useradd_parse_requirements() {
 
 }
 
+# :command.parse_requirements
+mush_userdel_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        mush_userdel_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="userdel"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        if [[ -z ${args['username']+x} ]]; then
+
+          args['username']=$1
+          shift
+        else
+          printf "invalid argument: %s\n" "$key" >&2
+          exit 1
+        fi
+
+        ;;
+
+    esac
+  done
+
+  # :command.required_args_filter
+  if [[ -z ${args['username']+x} ]]; then
+    printf "missing required argument: USERNAME\nusage: mush userdel USERNAME\n" >&2
+    exit 1
+  fi
+
+}
+
+# :command.parse_requirements
+mush_list_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        mush_list_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="list"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -537,6 +746,8 @@ run() {
   case "$action" in
     "init") mush_init_command ;;
     "useradd") mush_useradd_command ;;
+    "userdel") mush_userdel_command ;;
+    "list") mush_list_command ;;
   esac
 }
 
