Run bashly generate

diff --git a/mush b/mush
--- a/mush
+++ b/mush
@@ -356,10 +356,20 @@ mush_useradd_command() {
 # :command.function
 mush_userdel_command() {
   # src/userdel_command.sh
-  echo "# this file is located in 'src/userdel_command.sh'"
-  echo "# code for 'mush userdel' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
+  username=${args[username]}
+
+  if [[ -z $username ]]; then
+      echo "username is required"
+      exit 1
+  fi
+
+  result=$(userdel -r $username)
+  if [[ $result == "userdel: user '$username' does not exist" ]]; then
+      echo "user does not exist"
+      exit 1
+  fi
+
+  echo "User deleted successfully"
 
 }
 
