Add init command

diff --git a/mush b/mush
--- a/mush
+++ b/mush
@@ -34,8 +34,8 @@ mush_usage() {
   echo
   # :command.usage_commands
   printf "%s\n" "Commands:"
+  printf "  %s   Initialize the mush\n" "init   "
   printf "  %s   Add a new user\n" "useradd"
-  printf "  %s   \n" "test   "
   echo
 
   # :command.long_usage
@@ -48,6 +48,44 @@ mush_usage() {
     echo
     printf "  %s\n" "--version, -v"
     printf "    Show version number\n"
+    echo
+
+  fi
+}
+
+# :command.usage
+mush_init_usage() {
+  if [[ -n $long_usage ]]; then
+    printf "mush init - Initialize the mush\n"
+    echo
+
+  else
+    printf "mush init - Initialize the mush\n"
+    echo
+
+  fi
+
+  printf "Alias: i\n"
+  echo
+
+  printf "%s\n" "Usage:"
+  printf "  mush init [OPTIONS]\n"
+  printf "  mush init --help | -h\n"
+  echo
+
+  # :command.long_usage
+  if [[ -n $long_usage ]]; then
+    printf "%s\n" "Options:"
+
+    # :command.usage_flags
+    # :flag.usage
+    printf "  %s\n" "--force, -f"
+    printf "    Force initialization even if the files already exist\n"
+    echo
+
+    # :command.usage_fixed_flags
+    printf "  %s\n" "--help, -h"
+    printf "    Show this help\n"
     echo
 
   fi
@@ -99,35 +137,6 @@ mush_useradd_usage() {
     printf "    Traffic limit of the new user\n"
     printf "    Default: 20GB\n"
     echo
-
-    # :command.usage_fixed_flags
-    printf "  %s\n" "--help, -h"
-    printf "    Show this help\n"
-    echo
-
-  fi
-}
-
-# :command.usage
-mush_test_usage() {
-  if [[ -n $long_usage ]]; then
-    printf "mush test\n"
-    echo
-
-  else
-    printf "mush test\n"
-    echo
-
-  fi
-
-  printf "%s\n" "Usage:"
-  printf "  mush test\n"
-  printf "  mush test --help | -h\n"
-  echo
-
-  # :command.long_usage
-  if [[ -n $long_usage ]]; then
-    printf "%s\n" "Options:"
 
     # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
@@ -191,6 +200,36 @@ inspect_args() {
 
 # :command.command_functions
 # :command.function
+mush_init_command() {
+  # src/init_command.sh
+  CONFIG_DIR="$HOME/.mush"
+  USERS_FILE="$CONFIG_DIR/users.json"
+  LOG_FILE="$CONFIG_DIR/mush.log"
+  CRON_FILE="$CONFIG_DIR/cron.sh"
+
+  force=${args[--force]}
+
+  if [[ -d $CONFIG_DIR && -z $force ]]; then
+      echo "Mush is already initialized"
+      exit 1
+  fi
+
+  if [[ -d $CONFIG_DIR && -n $force ]]; then
+      rm -rf $CONFIG_DIR
+  fi
+
+  mkdir -p $CONFIG_DIR
+
+  echo "[]" > $USERS_FILE
+  touch $LOG_FILE
+  touch $CRON_FILE
+  chmod +x $CRON_FILE
+  # TODO: add cron job
+
+  echo "Mush initialized successfully"
+}
+
+# :command.function
 mush_useradd_command() {
   # src/useradd_command.sh
   username=${args[--username]}
@@ -215,16 +254,6 @@ mush_useradd_command() {
   echo "User created successfully"
   echo "Username: $username"
   echo "Password: $password"
-}
-
-# :command.function
-mush_test_command() {
-  # src/test_command.sh
-  echo "# this file is located in 'src/test_command.sh'"
-  echo "# code for 'mush test' goes here"
-  echo "# you can edit it freely and regenerate (it will not be overwritten)"
-  inspect_args
-
 }
 
 # :command.parse_requirements
@@ -256,17 +285,17 @@ parse_requirements() {
   case $action in
     -*) ;;
 
+    init | i)
+      action="init"
+      shift
+      mush_init_parse_requirements "$@"
+      shift $#
+      ;;
+
     useradd | u)
       action="useradd"
       shift
       mush_useradd_parse_requirements "$@"
-      shift $#
-      ;;
-
-    test)
-      action="test"
-      shift
-      mush_test_parse_requirements "$@"
       shift $#
       ;;
 
@@ -287,6 +316,57 @@ parse_requirements() {
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
+
+      -?*)
+        printf "invalid option: %s\n" "$key" >&2
+        exit 1
+        ;;
+
+      *)
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
+        printf "invalid argument: %s\n" "$key" >&2
+        exit 1
+
+        ;;
+
+    esac
+  done
+
+}
+
+# :command.parse_requirements
+mush_init_parse_requirements() {
+  # :command.fixed_flags_filter
+  while [[ $# -gt 0 ]]; do
+    case "${1:-}" in
+      --help | -h)
+        long_usage=yes
+        mush_init_usage
+        exit
+        ;;
+
+      *)
+        break
+        ;;
+
+    esac
+  done
+
+  # :command.command_filter
+  action="init"
+
+  # :command.parse_requirements_while
+  while [[ $# -gt 0 ]]; do
+    key="$1"
+    case "$key" in
+      # :flag.case
+      --force | -f)
+
+        # :flag.case_no_arg
+        args['--force']=1
+        shift
+        ;;
 
       -?*)
         printf "invalid option: %s\n" "$key" >&2
@@ -413,50 +493,6 @@ mush_useradd_parse_requirements() {
 
 }
 
-# :command.parse_requirements
-mush_test_parse_requirements() {
-  # :command.fixed_flags_filter
-  while [[ $# -gt 0 ]]; do
-    case "${1:-}" in
-      --help | -h)
-        long_usage=yes
-        mush_test_usage
-        exit
-        ;;
-
-      *)
-        break
-        ;;
-
-    esac
-  done
-
-  # :command.command_filter
-  action="test"
-
-  # :command.parse_requirements_while
-  while [[ $# -gt 0 ]]; do
-    key="$1"
-    case "$key" in
-
-      -?*)
-        printf "invalid option: %s\n" "$key" >&2
-        exit 1
-        ;;
-
-      *)
-        # :command.parse_requirements_case
-        # :command.parse_requirements_case_simple
-        printf "invalid argument: %s\n" "$key" >&2
-        exit 1
-
-        ;;
-
-    esac
-  done
-
-}
-
 # :command.initialize
 initialize() {
   version="0.1.0"
@@ -477,8 +513,8 @@ run() {
   parse_requirements "${input[@]}"
 
   case "$action" in
+    "init") mush_init_command ;;
     "useradd") mush_useradd_command ;;
-    "test") mush_test_command ;;
   esac
 }
 
